import type { LunarCrushCapability } from "@/types/integration.types"

export const LUNARCRUSH_CAPABILITIES: LunarCrushCapability[] = [
  {
    id: "social_sentiment_tracking",
    name: "Social Sentiment Tracking",
    description: "Track real-time social sentiment across Twitter, Reddit, and other platforms",
    category: "social",
    enabled: false,
    nodeType: "marketMonitor",
    propertyType: "trigger",
    variables: ["social_sentiment", "social_mentions", "social_engagement"],
    endpoint: "/public/coins/list",
  },
  {
    id: "influencer_activity",
    name: "Influencer Activity Monitor",
    description: "Monitor crypto influencer posts and engagement metrics",
    category: "influencer",
    enabled: false,
    nodeType: "notification",
    propertyType: "trigger",
    variables: ["social_mentions", "social_engagement"],
    endpoint: "/public/influencers",
  },
  {
    id: "galaxy_score",
    name: "Galaxy Score™",
    description: "LunarCrush's proprietary social health score (0-100)",
    category: "galaxy",
    enabled: false,
    nodeType: "technicalIndicator",
    propertyType: "condition",
    variables: ["social_sentiment"],
    endpoint: "/public/coins/list",
  },
  {
    id: "alt_rank",
    name: "AltRank™",
    description: "Relative ranking of altcoins based on social and market metrics",
    category: "market",
    enabled: false,
    nodeType: "marketMonitor",
    propertyType: "condition",
    variables: ["market_cap_rank"],
    endpoint: "/public/coins/list",
  },
  {
    id: "social_volume_alerts",
    name: "Social Volume Alerts",
    description: "Get alerted when social volume spikes above threshold",
    category: "social",
    enabled: false,
    nodeType: "priceAlert",
    propertyType: "trigger",
    variables: ["social_mentions", "volume_change_24h"],
    endpoint: "/public/coins/list",
  },
  {
    id: "trending_coins",
    name: "Trending Coins",
    description: "Identify coins trending on social media in real-time",
    category: "social",
    enabled: false,
    nodeType: "marketMonitor",
    propertyType: "trigger",
    variables: ["social_mentions", "social_engagement"],
    endpoint: "/public/coins/trending",
  },
  {
    id: "market_dominance",
    name: "Market Dominance",
    description: "Track social dominance vs market cap dominance",
    category: "market",
    enabled: false,
    nodeType: "technicalIndicator",
    propertyType: "condition",
    variables: ["market_cap", "social_engagement"],
    endpoint: "/public/coins/list",
  },
  {
    id: "nft_social_metrics",
    name: "NFT Social Metrics",
    description: "Track social sentiment and engagement for NFT collections",
    category: "nft",
    enabled: false,
    nodeType: "marketMonitor",
    propertyType: "trigger",
    variables: ["social_sentiment", "social_mentions"],
    endpoint: "/public/nfts",
  },
]
